language: php

sudo: required

addons:
  apt:
    sources:
    - sourceline: ppa:ondrej/php
    packages:
    - libsodium-dev

php:
- 7.0
- 7.1
- 7.2

env:
  global:
  - PHPCS=0

cache:
  directories:
  - "$HOME/.composer/cache"

matrix:
  fast_finish: true

  include:
  - php: 7.1
    env: PHPCS=1

before_script:
- if [[ $TRAVIS_PHP_VERSION != 7.2 ]]; then rm -f composer.lock; fi
- composer install --prefer-dist --no-interaction
- composer require paragonie/sodium_compat;
- if [[ $TRAVIS_PHP_VERSION != 7.2 ]]; then pecl install libsodium; fi

script:
- if [[ $PHPCS != 1 ]]; then composer test; fi
- if [[ $PHPCS = 1 ]]; then composer cs; fi

notifications:
  email: false